# Project information
site_name: 'Python Essential'
site_description: 'Навчальний курс з програмування мовою Python. Необхідне.'
site_author: 'Ruslan Iskov'

use_directory_urls: false
strict: true
dev_addr: '127.0.0.1:8010'

site_dir: '.\docs'
docs_dir: '.\source'

site_url: '' # TODO



# Repository
### repo_name: 'squidfunk/mkdocs-material'
### repo_url: 'https://github.com/squidfunk/mkdocs-material'
#repo_name: 'winter design school'
#repo_url: 'http://ruslan.rv.ua/winter_design_school/'
# remote_branch: master


# Copyright
copyright: 'Copyright &copy; Ruslan Iskov'

# Configuration
theme:
  name: material
  language: uk
  icon:
    logo: material/language-python
    # logo: fontawesome/brands/python
  # favicon: fontawesome/brands/python.svg
  palette:
    scheme: slate # default
    primary: 'black'
    accent: 'yellow'
  features:
    - header.autohide
    - navigation.instant
    # or - navigation.tabs
    # or - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    # - toc.integrate
    # - navigation.indexes
    - navigation.top

# css overrides to make high contrast theme
extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/fixes.css

# switch off plugins, it's for removing 'search' feature
plugins: []
# plugins:
 # - search
 # - awesome-pages:
   # collapse_single_pages: true
        
# Customization
extra:
  # disqus: <shortname>
  generator: false
#   social:
#    - type: 'github'
#      link: 'https://github.com/squidfunk'
#    - type: 'twitter'
#      link: 'https://twitter.com/squidfunk'
#    - type: 'linkedin'
#      link: 'https://linkedin.com/in/squidfunk'
#    search:
#        language: 'en, ru'
    

# Google Analytics
# google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  # - toc:
      # permalink: false
      # slugify: !!python/name:pymdownx.slugs.uslugify
      # toc_depth: 3
  - admonition
  - codehilite:
      guess_lang: false
      css_class: codehilite
      # pygments_style: agate
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.tilde

nav:
  - Про цей курс: index.md
  - Підготовка: preparations.md
  - Парадигми програмування:
    - Парадигми у програмуванні: paradigmas/paradigmas.md
    - Імперативне програмування: paradigmas/imperative.md
    - Об'єктно-орієнтоване програмування: paradigmas/oop.md
    - Декларативне програмування: paradigmas/declarative.md
    - Резюме: paradigmas/resume.md
  - Функції:
    - Параметри функцій: 
      - Позиційні та іменовані: functions/args/pos_and_kw.md
      - Опціональні: functions/args/default.md
      - Лише позиційні або іменовані: functions/args/pos_and_kw_only.md
      - Довільна кількість аргументів: functions/args/args_kwargs.md
    - Стратегії обчислення: functions/strategies.md
    - Простори імен: functions/scope.md
    - Стек викликів: functions/call_stack.md
    - Документування функцій: functions/docstring.md
  - Об'єктно-орієнтоване програмування:
    - Парадигма ООП: oop/oop_basis.md
    - Класи і об'єкти:
      - ООП в Python: oop/classes.md
      - Життєвий цикл об'єкта: oop/object_lifecycle.md
      - Ініціалізація об'єктів: oop/init.md
      - Представлення об'єктів: oop/object_presentation.md
    - Інкапсуляція:
      - Інкапсуляція в ООП: oop/encapsulation/encapsulation_basis.md
      - Приховування атрибутів: oop/encapsulation/hiding_attrs.md
      - Сетери і гетери: oop/encapsulation/setters_and_getters.md
      - Властивості: oop/encapsulation/properties.md
      - Обчислювані властивості: oop/encapsulation/calc_props.md
    - Успадкування:
      - Успадкування в ООП: oop/inheritance/inheritance_basis.md
      - Успадкування в Python: oop/inheritance/inheritance_python.md
      - Успадкування атрибутів: oop/inheritance/attrs_inheritance.md
      - Лінеаризація: oop/inheritance/linearization.md
      - Множинне успадкування: oop/inheritance/multiple_inheritance.md
      - Атрибути базового класа: oop/inheritance/call_overrided.md
      - Резюме: oop/inheritance/recap.md
    - Поліморфізм:
      - Поліморфізм в ООП: oop/polymorphism/polymorphism_basis.md
      - Поліморфізм в Python: oop/polymorphism/polymorphism_python.md
    - Статичні та класові методи: oop/static_and_class_methods.md
    # TODO: hasattr, setattr, ...
    - Доступ до атрибутів: oop/behavior/attributes.md
  - Виняткові ситуації:
    - Винятки: exceptions/exceptions.md
    - '"Підйом" винятків': exceptions/exceptions_raising.md
    # TODO: - assert
    - Обробка винятків: exceptions/exceptions_handling.md
    - Попередження: exceptions/warnings.md
    - EAFP vs LBYL: exceptions/eafp_vs_lbyl.md
    - Менеджери контекста: exceptions/context_manager.md
  - Ітератори та генератори:
    - Ітерабельні об'єкти: iterable/iterable.md
    - Ітератори: iterable/iterator.md
    - Реалізація за допомогою __iter__: iterable/magic_iter.md
    - Реалізація за допомогою __getitem__: iterable/magic_getitem.md
    - Генератори: iterable/generator.md
    - Генератори-вирази: iterable/generator_expressions.md
    - Упаковка та розпаковка ітерабельних об'єктів: iterable/starr.md
  # - Елементи функціонального програмування:
    # - Парадигма ФП: functional_programming/intro.md
    # - Чисті функції: functional_programming/pure_functions.md
    # - Функції вищого порядку: functional_programming/higher_order_functions.md
    # - Анонімні функції: functional_programming/lambda.md
    # - Функції map(), filter(), zip(): functional_programming/map_filter.md
    # - Рекурсія: functional_programming/recursion.md
    # - Замикання: functional_programming/closure.md
    # - Декоратори: functional_programming/decorator.md
  - Ввід та вивід:
    - Файли і потоки: io/files_and_streams.md
    - Відкриття і закриття потоків: io/open_close.md
    - Читання і запис: io/read_write.md
    - Серіалізація об'єктів: io/serialization.md    
  - Модулі і пакети:
    - Модулі у програмуванні: modules_and_packages/module.md
    - Модулі в Python: modules_and_packages/module_python.md
    - Модулі як об'єкти: modules_and_packages/module_object.md
    - Пакети: modules_and_packages/packages.md
    - Встановлення пакетів: modules_and_packages/pip.md
  - Виконання програм:
    - Інтерпретатор Python: interpreter/interpreter.md
    # - Програмне виконання коду: interpreter/
    - Передача аргументів скрипту: interpreter/args.md
    - Віртуальні оточення: interpreter/venv.md
  - Типи та структури даних:
    # - Типізація:
    - Типізація у програмуванні: types_and_data_structures/typing.md
      # - Типізація в Python: types_and_data_structures/type_hinting.md
    - Числа:
      - Системи числення: types_and_data_structures/numbers/number_system.md
      - Цілі числа: types_and_data_structures/numbers/int.md
      - Дійсні числа: types_and_data_structures/numbers/float.md
      - Комплексні числа: types_and_data_structures/numbers/complex.md
      # - Булевий тип даних: types_and_data_structures/numbers/bool.md
    - Контейнери:
      - Колекції в Python: types_and_data_structures/collections/collections.md
      - Послідовності:
        - Послідовності в Python: types_and_data_structures/sequences/sequences.md
        - Списки: types_and_data_structures/sequences/list.md
        - Кортежі: types_and_data_structures/sequences/tuple.md
        - Діапазони: types_and_data_structures/sequences/range.md
        - Символьні рядки: types_and_data_structures/sequences/str.md
        - Бінарні послідовності: types_and_data_structures/sequences/bin_seq.md
        # - Порівняння послідовностей: types_and_data_structures/sequences/seq_compare.md
      - Відображення та множини:
        - Хешування даних: types_and_data_structures/mappings_and_sets/hash.md
        - "Об'єкти, що хешуються": types_and_data_structures/mappings_and_sets/hashable.md
        - Відображення в Python: types_and_data_structures/mappings_and_sets/mapingss.md
        # - Множини в Python: types_and_data_structures/mappings_and_sets/sets.md
  - Батарейки:
    - Модуль datetime: batteries/datetime.md
    - Модуль collections: batteries/collections.md
    - Модуль path: batteries/os_path.md
    - Модуль itertools: batteries/itertools.md
    # - Модуль functools: batteries/functools.md
    - Модуль    : batteries/contextlib.md
  - Наступні кроки:
    - Що далі?: go_ahead/whats_next.md
    - Корисні ресурси: go_ahead/resources.md
    - Міфи про навчання: go_ahead/miths_edu.md

